{{- if .Values.dopplerSecret.enabled }}
apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: {{ .Values.dopplerSecret.secretName }}
  labels:
    {{- include "car-lookup-service.labels" . | nindent 4 }}
spec:
  tokenSecret:
    name: doppler-token-secret
  managedSecret:
    name: {{ .Values.dopplerSecret.secretName }}
    namespace: {{ .Release.Namespace }}
  project: {{ .Values.dopplerSecret.project }}
  config: {{ .Values.dopplerSecret.config }}
{{- end }}
